version: 2
jobs:
  build:
    docker:
      - image: python:3.8
    steps:
      - checkout

      - run: 
          name: Install torchdiffeq and output `pip list`
          command: |
            python setup.py install
            pip list

      - run: 
          name: Run tests
          command: |
            mkdir test-results
            pip install pytest
            pytest --junitxml=test-results/junit.xml tests/run_all.py

      - store_test_results:
          path: test-results