version: 2
jobs:
  build:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run: 
          name: Check Python version
          command: |
            python --version; pip list
      - run: python setup.py install; pip list
      - run: 
          name: Running tests
          command: |
            python tests/run_all.py
      - store_test_results:
        path: test-results